### ISSUE TITLE
[Plater] TBC issues and LUA errors when moving Plugins/Displays on a bar everything disappears. 

### ISSUE THREAD

**Issue by PsiloCA** [Kiatra/ChocolateBar#14] opened 2021-06-15 18:16 UTC
Here are a few LUA errors I have encountered recently in the Classic version of TBC. When trying to move any of the plugins displays on the bar the whole thing seems to crash and all the bars vanish and I receive these lua errors. I can only get the bars back after doing a UI reload. been a big fan of this app and its customization for many many years now. 

here are the 2 lua errors taken from the game.

LUA error #1

6x ChocolateBar\Chocolate.lua:325: Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: NamePlate1PlaterUnitFrame:GetPoint().
[string "=[C]"]: in function `GetPoint'
[string "@ChocolateBar\Chocolate.lua"]:325: in function <ChocolateBar\Chocolate.lua:307>

Locals:
(*temporary) = NamePlate1PlaterUnitFrame {
UpdateUnitFrame = <function> defined @Details\Libs\DF\panel.lua:9179
UnitFrameEvents = <table> {
}
Plater = true
ActorType = "friendlyplayer"
InExecuteRange = false
namePlateThreatOffTankIsTanking = false
OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:239
namePlateUnitReaction = 5
castBar = NamePlate1PlaterUnitFrameCastBar {
}
GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:477
IsProtected = <function> defined @Plater\Plater.lua:9790
SetUnit = <function> defined @Details\Libs\DF\panel.lua:8956
namePlateUnitGUID = "Player-4373-01C90016"
Top3DFrame = NamePlate13DFrame {
}
CustomIndicators = <table> {
}
namePlateUnitNameLower = "stimmyme"
TargetTextures4Sides = <table> {
}
targetOverlay = <unnamed> {
}
CanCheckAggro = false
ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:369
PlaterRaidTargetFrame = <unnamed> {
}
ScriptGetContainer = <function> defined @Plater\Plater.lua:9543
PlayerCannotAttack = true
SetAlphaTo = <function> defined @Plater\Plater.lua:7667
ActorNameSpecial = <unnamed> {
}
UNIT_EXITED_VEHICLE = <function> defined @Details\Libs\DF\panel.lua:9214
UNIT_CONNECTION = <function> defined @Details\Libs\DF\panel.lua:9224
aggroGlowUpper = <unnamed> {
}
OnHideWidget = <function> defined @Plater\Plater.lua:9714
UpdateHealthColor = <function> defined @Details\Libs\DF\panel.lua:9039
0 = <userdata>
OnTick = <function> defined @Details\Libs\DF\panel.lua:8929
isNamePlate = true
unit = "nameplate1"
HasHideHookRegistered = true
UnregisterEvents = <function> defined @Details\Libs\DF\panel.lua:8917
SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:301
QuestInfo = <table> {
}
HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:365
WidgetType = "unitFrame"
IsTarget = false
unitName = <unnamed> {
}
isPlayer = true
GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:275
RegisterEvents = <function> defined @Details\Libs\DF\panel.lua:8891
TargetNeonDown = <unnamed> {
}
powerBar = NamePlate1PlaterUnitFramePowerBar {
}
IsUnitNameplate = true
ExtraIconFrame = NamePlate1PlaterUnitFrameExtraIconRow {
}
ScriptRunInitialization = <function> defined @Plater\Plater.lua:9668
RefreshID = 6
namePlateUnitToken = "nameplate1"
ScriptRunOnShow = <function> defined @Plater\Plater.lua:9634
UpdateAllWidgets = <function> defined @Details\Libs\DF\panel.lua:9155
namePlateUnitName = "Stimmyme"
ScriptRunNoAttach = <function> defined @Plater\Plater.lua:9702
displayedUnit = "nameplate1"
InCombat = false
TargetNeonUp = <unnamed> {
}
IsUnitEvent = <table> {
}
IsUIParent = true
namePlateThreatPercent = 0
PlateFrame = NamePlate1 {
}
PLAYER_ENTERING_WORLD = <function> defined @Details\Libs\DF\panel.lua:9189
CheckVehiclePossession = <function> defined @Details\Libs\DF\panel.lua:9005
namePlateIsQuestObjective = false
namePlateInRange = true
HighlightFrame = NamePlate1PlaterUnitFrameHealthBarHighlightOverlay {
}
AuraCache = <table> {
}
blizzardPlateFrameID = "table: 00000123AFD99E70"
ScriptHotReload = <function> defined @Plater\Plater.lua:9595
ScriptRunOnUpdate = <function> defined @Plater\Plater.lua:9614
GetBackdrop = <function> defined @SharedXML\Backdrop.lua:434
castBar2 = NamePlate1PlaterUnitFrameCastBar2 {
}
ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:381
PARTY_MEMBER_ENABLE = <function> defined @Details\Libs\DF\panel.lua:9229
healthBar = NamePlate1PlaterUnitFrameHealthBar {
}
FocusIndicator = <unnamed> {
}
BossModIconFrame = NamePlate1PlaterUnitFrameHealthBarBossModIconRow {
}
BodyFlashFrame = <unnamed>

 

-----------------------------------------------------------------------

LUA error #2

 

6x ChocolateBar\DragAndDrop.lua:86: attempt to index upvalue 'focus' (a nil value)
[string "@ChocolateBar\DragAndDrop.lua"]:86: in function `Stop'
[string "@ChocolateBar\Chocolate.lua"]:347: in function <ChocolateBar\Chocolate.lua:341>

Locals:
self = <table> {
Start = <function> defined @ChocolateBar\DragAndDrop.lua:67
UnregisterFrame = <function> defined @ChocolateBar\DragAndDrop.lua:63
Stop = <function> defined @ChocolateBar\DragAndDrop.lua:79
RegisterFrame = <function> defined @ChocolateBar\DragAndDrop.lua:54
}
frame = ChocolateBartender4 {
BottomLeftCorner = <unnamed> {
}
OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:239
GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:477
SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:509
icon = <unnamed> {
}
obj = <table> {
}
text = <unnamed> {
}
SetBackdrop = <function> defined @SharedXML\Backdrop.lua:416
ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:369
GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:496
GetBackdrop = <function> defined @SharedXML\Backdrop.lua:434
bar = ChocolateBar1 {
}
SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:353
highlight = <function> defined @ChocolateBar\Chocolate.lua:355
Update = <function> defined @ChocolateBar\Chocolate.lua:300
isMoving = false
settings = <table> {
}
OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:269
HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:365
Center = <unnamed> {
}
RightEdge = <unnamed> {
}
GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:275
labelText = ""
0 = <userdata>
TopEdge = <unnamed> {
}
BottomEdge = <unnamed> {
}
name = "Bartender4"
BottomRightCorner = <unnamed> {
}
TopRightCorner = <unnamed> {
}
TopLeftCorner = <unnamed> {
}
SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:301
backdropInfo = <table> {
}
SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:333
SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:486
LeftEdge = <unnamed> {
}
ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:381
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "OnUpdate"
(*temporary) = nil
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = ChocolateBar3 {
0 = <userdata>
UpdateBar = <function> defined @ChocolateBar\Bar.lua:428
GetFocus = <function> defined @ChocolateBar\Bar.lua:421
OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:239
GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:477
autohide = false
Drop = <function> defined @ChocolateBar\Bar.lua:394
UpdateColors = <function> defined @ChocolateBar\Bar.lua:121
SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:509
UpdateStrata = <function> defined @ChocolateBar\Bar.lua:76
New = <function> defined @ChocolateBar\Bar.lua:28
EatChocolatePiece = <function> defined @ChocolateBar\Bar.lua:184
tempHide = false
chocoMostRight = ChocolateGuild {
}
chocolist = <table> {
}
ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:381
SetBackdrop = <function> defined @SharedXML\Backdrop.lua:416
ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:369
LoseFocus = <function> defined @ChocolateBar\Bar.lua:417
GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:496
GetBackdrop = <function> defined @SharedXML\Backdrop.lua:434
listCenter = <table> {
}
chocoMostLeft = ChocolateGold {
}
UpdateDragChocolate = <function> defined @ChocolateBar\Bar.lua:346
SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:353
Center = <unnamed> {
}
RightEdge = <unnamed> {
}
UpdateScale = <function> defined @ChocolateBar\Bar.lua:105
LeftEdge = <unnamed> {
}
Drag = <function> defined @Interface

**Comment by plater** [comment] 2021-06-16 05:27
Hi, I'm user plater and I would like you to refrain from using @plater in your issues as it spams me with emails that have nothing to do with me. My name is Dave Plater unfortunately

**Comment by alexandre-mckinnon** [comment] 2022-11-04 03:15
Seems to be a duplicate of #2

**Comment by Kiatra** [comment] 2022-12-05 17:09
Dublicate of #2

**Closed by Kiatra** 2022-12-05 17:09 UTC
Labels: duplicate
